FROM python:3.12-slim

WORKDIR /app

COPY requirements-airflow.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY bento_service.py .
COPY 1_scaler.pkl .

EXPOSE 3000

CMD ["bentoml", "serve", "bento_service:CareerRecommendationService", "--host", "0.0.0.0", "--port", "3000"]
